### ISSUE TITLE
Скрипт рабочий?

### ISSUE THREAD

**Issue by ReZet** [yandex-php/php-yandex-locator#1]
Возвращает у меня ошибку "{"error": { "code" : 6, "text" : "Location not found"}}"
Токен задал, айпишник с $_SERVER['REMOTE_ADDR'] беру, а ошибка никуда не пропадает.
В чем может быть дело? Или яндекс.локатор не работает?

**Comment by dmtrkzntsv** [comment]
А какой IP?

**Comment by ReZet** [comment]
87.76.6.44

**Comment by dmtrkzntsv** [comment]
Извиняюсь за долгий ответ.
Попробовал получить инфу по вашему IP

```
class Yandex\Locator\Response#3 (1) {
  protected $_data =>
  array(1) {
    'position' =>
    array(6) {
      'latitude' =>
      double(54.3069534)
      'longitude' =>
      double(48.412159)
      'altitude' =>
      double(0)
      'precision' =>
      int(100000)
      'altitude_precision' =>
      double(30)
      'type' =>
      string(2) "ip"
    }
  }
}
```

У меня ошибок не наблюдается, скрипт работает корректно. 
С другими IP та же самая ошибка?

Мой test.php

``` php
<?php
require 'autoload.php';

$api = new \Yandex\Locator\Api('token');
$api->setIp('87.76.6.44');

$api->load();
$response = $api->getResponse();
var_dump($response);
```
